name: Django CI/CD

on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.12.8'
    - name: Secret Example
      run: |
          echo "AWS_USERNAME: ${{ secrets.AWS_USERNAME }}"
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    - name: Deploy to AWS EC2
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.AWS_HOST }}
        USERNAME: ${{ secrets.AWS_USERNAME }}
        KEY: ${{ secrets.DEPLOY_KEY }}
        PORT: 22
      with:
        source: "."
        target: "Project/"