name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Copy project to AWS EC2
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        ARGS: "-avz --delete"
        SOURCE: "."
        REMOTE_HOST: ${{ secrets.AWS_HOST }}
        REMOTE_USER: ${{ secrets.AWS_USERNAME }}
        TARGET: '/home/'${{ secrets.AWS_USERNAME }}'/actions-runner/_work/Newsify/'
#    - name: Install dependencies and restart server
#      run: |
#        ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} << 'EOF'
#          cd /path/to/your/project
#          source venv/bin/activate
#          pip install -r requirements.txt
#          sudo systemctl restart your-service.service
#        EOF