name: CI

# Указывает, когда действие должно быть выполнено
on:
  push:
    branches: [ master ]

# Задания, которые выполняются в рамках workflow
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Check Python version
        run: |
          echo "Установлена версия Python:"
          python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          echo "Установка pip обновлена."
          pip install -r requirements.txt
          echo "Зависимости установлены."

      - name: Run tests
        run: |
          echo "Запуск тестов..."
          python manage.py test
          echo "Тесты завершены."