name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Copy project to AWS EC2
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        ARGS: "-avz --delete"
        SOURCE: "."
        REMOTE_HOST: ${{ secrets.AWS_HOST }}
        REMOTE_USER: ${{ secrets.AWS_USERNAME }}
        TARGET: 'newsify'
    - name: Install dependencies and start server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          sudo apt update
            sudo apt install -y python3-venv
            cd newsify
            echo "${{ secrets.ENV }}" > .env
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            python3 manage.py migrate --noinput
            python3 manage.py collectstatic --no-input
            python3 manage.py runserver
            gunicorn newsify.wsgi:application --bind 0.0.0.0:8000 --daemon
