name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copy project to AWS EC2
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        ARGS: "-avz --delete"
        SOURCE: "."
        REMOTE_HOST: ${{ secrets.AWS_HOST }}
        REMOTE_USER: ${{ secrets.AWS_USERNAME }}
        TARGET: 'newsify'

    - name: Install dependencies and restart server
      run: |
        ssh -tt -o StrictHostKeyChecking=no ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} << 'EOF'
          cd newsify
          pip install -r requirements.txt
          pkill -f "manage.py runserver" || true  # Остановка старого сервера
          nohup python3 manage.py runserver 0.0.0.0:8000 > server.log 2>&1 &
        EOF
